branch-defaults:
  default:
    environment: ToDoApplication-backend-dev
    group_suffix: null
global:
  application_name: ToDoApplication-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
deploy:
  artifact: build/libs/demo-0.0.1-SNAPSHOT.jar
